-- 35 productos Por Encargo (Sephora) — 2026-09-25
--
-- Datos sacados del JSON-LD de cada ficha de Sephora: nombre oficial, marca,
-- categoria y foto principal. Las 35 fotos fueron verificadas una por una
-- (1000x1000 reales, ninguna rota ni placeholder).
--
-- precio 0 y sin costo/stock: es la convencion de los Por Encargo que ya
-- estaban cargados — tienePrecioPublico() los deja sin precio a la vista y se
-- cotizan por consulta.
--
-- Los slugs se generaron con la funcion real del proyecto (lib/slug.ts)
-- verificando que no choquen con los 38 que ya existen: 73 unicos en total.
--
-- IMPORTANTE — las fotos apuntan a sephora.com. El optimizador de imagenes
-- solo acepta el bucket propio, asi que se van a ver rotas hasta que corras:
--
--     node scripts/migrar-imagenes.mjs
--
-- Corré ese script JUSTO DESPUES de este SQL. Baja cada foto, la comprime
-- igual que el admin (800px, webp) y la sube a tu bucket.
--
-- Descripciones: 19 salen de la ficha oficial del producto. Las otras
-- 16 (13, 14, 19, 20, 21, 22, 23, 24, 25, 26, 29, 30, 31, 32, 33, 35) estan redactadas a partir
-- del nombre oficial, sin inventar datos, porque Sephora bloqueo la lectura
-- de esas fichas. Editalas desde el admin cuando quieras.

insert into public.productos
  (nombre, marca, categoria, subcategoria, estado, precio,
   descripcion_corta, descripcion_larga, imagen_url, slug, orden_display)
values
  ('Bio Collagen Real Deep Mask for Pore Minimizing & Firming Care', 'Biodance', 'Skincare', 'Skincare', 'Por Encargo', 0, 'Mascarilla facial en gel concentrado que hidrata, mejora la elasticidad y afina los poros.', 'Mascarilla facial de gel altamente concentrado que se adhiere como una segunda piel. Aporta hidratación intensa, mejora la elasticidad y reduce la apariencia de los poros. Se deja actuar hasta que el gel se vuelve transparente y no necesita enjuague: el excedente se masajea sobre la piel.', 'https://www.sephora.com/productimages/sku/s2865186-main-zoom.jpg?imwidth=1000', 'biodance-bio-collagen-real-deep-mask-for-pore-minimizing-y-firming', 101),
  ('Mini Pillow Talk Lipstick & Liner Set', 'Charlotte Tilbury', 'Maquillajes', 'Labios', 'Por Encargo', 0, 'Set mini con labial y delineador Pillow Talk, el nude rosado icónico de la marca.', 'Set en formato mini con el labial más vendido de Charlotte Tilbury y su delineador Lip Cheat a juego. Pillow Talk es el nude rosado que hizo famosa a la marca: favorece a la mayoría de los tonos de piel y da un efecto labios naturales pero definidos. Ideal para llevar en la cartera.', 'https://www.sephora.com/productimages/sku/s2801371-main-zoom.jpg?imwidth=1000', 'charlotte-tilbury-mini-pillow-talk-lipstick-y-liner-set', 102),
  ('Refillable Airbrush Matte Bronzer', 'Charlotte Tilbury', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Bronzer mate en polvo con ácido hialurónico, en estuche recargable.', 'Bronzer en polvo de acabado mate natural, formulado con ácido hialurónico para que no reseque ni marque la textura de la piel. Viene en un estuche recargable de tamaño generoso, pensado para usar tanto en el rostro como en el cuerpo. Da un efecto bronceado creíble, sin naranja.', 'https://www.sephora.com/productimages/sku/s2351187-main-zoom.jpg?imwidth=1000', 'charlotte-tilbury-refillable-airbrush-matte-bronzer', 103),
  ('Beauty Highlighter Wand', 'Charlotte Tilbury', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Iluminador líquido en aplicador tipo varita para un brillo natural.', 'Iluminador líquido con aplicador tipo varita que permite aplicar directo sobre la piel y difuminar con los dedos. Da un brillo luminoso y natural en los puntos altos del rostro. La textura líquida se funde con la base sin apelmazarse ni resaltar la textura de la piel.', 'https://www.sephora.com/productimages/sku/s2366524-main-zoom.jpg?imwidth=1000', 'charlotte-tilbury-beauty-highlighter-wand', 104),
  ('Hollywood Flawless Filter', 'Charlotte Tilbury', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Potenciador del cutis que difumina y da luz, efecto filtro real.', 'Potenciador del cutis que difumina, alisa e ilumina para un efecto filtro en la vida real. Se puede usar de cuatro formas: solo para unificar, mezclado con la base, encima como iluminador o en puntos concretos. Deja la piel con aspecto luminoso y sin marcar poros.', 'https://www.sephora.com/productimages/sku/s2419786-main-zoom.jpg?imwidth=1000', 'charlotte-tilbury-hollywood-flawless-filter', 105),
  ('Benetint Lip & Cheek Stain', 'Benefit Cosmetics', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Tinta labial y de mejillas resistente al agua, color buildable de larga duración.', 'Tinta líquida para labios y mejillas, resistente al agua y de larga duración. El color es buildable: con una gota se logra un rubor natural y se puede intensificar capa a capa. No se transfiere ni se desvanece durante el día, y deja un acabado radiante y natural. Un clásico de Benefit.', 'https://www.sephora.com/productimages/sku/s2869519-main-zoom.jpg?imwidth=1000', 'benefit-cosmetics-benetint-lip-y-cheek-stain', 106),
  ('Hoola Matte Powder Bronzer', 'Benefit Cosmetics', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Bronzer en polvo de textura sedosa y acabado mate natural.', 'Bronzer en polvo galardonado, de textura sedosa y acabado mate natural. Se difumina con facilidad y sirve tanto para dar calidez al rostro como para contornear. El tono mate sin destellos lo hace fácil de usar a diario y en todo tipo de piel. Es el bronzer más vendido de Benefit.', 'https://www.sephora.com/productimages/sku/s2999316-main-zoom.jpg?imwidth=1000', 'benefit-cosmetics-hoola-matte-powder-bronzer', 107),
  ('Gloss Bomb Stix High-Shine Gloss Stick', 'Fenty Beauty by Rihanna', 'Maquillajes', 'Labios', 'Por Encargo', 0, 'Labial en stick con brillo intenso, vitamina E y manteca de karité.', 'Labial en formato stick con pigmentación media y brillo intenso. Está formulado con vitamina E y manteca de karité, que mantienen la hidratación por varias horas. La textura es cómoda y no pegajosa, y se puede aplicar directo sin espejo gracias al formato en barra.', 'https://www.sephora.com/productimages/sku/s3004314-main-zoom.jpg?imwidth=1000', 'fenty-beauty-by-rihanna-gloss-bomb-stix-high-shine-gloss-stick', 108),
  ('Diamond Bomb All-Over Diamond Veil', 'Fenty Beauty by Rihanna', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Iluminador en polvo con destellos tipo diamante para rostro y cuerpo.', 'Iluminador en polvo con partículas que reflejan la luz como diamantes. Se aplica como un velo brillante sobre rostro y cuerpo, y da un destello intenso que se nota a la distancia. Pensado para looks de noche o eventos, aunque en poca cantidad también funciona para el día.', 'https://www.sephora.com/productimages/sku/s2385169-main-zoom.jpg?imwidth=1000', 'fenty-beauty-by-rihanna-diamond-bomb-all-over-diamond-veil', 109),
  ('Honey Infused Hydrating Lip Oil', 'Gisou', 'Maquillajes', 'Labios', 'Por Encargo', 0, 'Aceite labial con miel Mirsalehi: hidratación, brillo y un toque de color.', 'Aceite labial con miel Mirsalehi, proveniente del apiario propio de la marca. Hidrata en profundidad y deja un brillo tipo gloss con un velo de color, sin la sensación pegajosa típica de los brillos. Tiene aroma dulce y se puede reaplicar durante el día como tratamiento.', 'https://www.sephora.com/productimages/sku/s3015534-main-zoom.jpg?imwidth=1000', 'gisou-honey-infused-hydrating-lip-oil', 110),
  ('Glassy High-Shine Lip Gloss', 'Glossier', 'Maquillajes', 'Labios', 'Por Encargo', 0, 'Gloss labial de acabado vidriado y brillo intenso, cómodo de llevar.', 'Gloss labial de brillo intenso y acabado vidriado. La fórmula tiene la adherencia justa para que dure sin resultar incómoda, y el aplicador deja una capa pareja de una sola pasada. Se puede usar solo o encima de un labial para sumarle luz y dimensión.', 'https://www.sephora.com/productimages/sku/s2831287-main-zoom.jpg?imwidth=1000', 'glossier-glassy-high-shine-lip-gloss', 111),
  ('Power Sculpt Velvet Talc-Free Powder Bronzer', 'Haus Labs', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Bronzer en polvo sin talco, con árnica fermentada y escualano.', 'Bronzer en polvo libre de talco y no comedogénico, formulado con árnica fermentada y escualano. Se difumina de forma pareja y difumina la textura de la piel mientras aporta calidez natural, con una duración declarada de hasta 12 horas. Textura aterciopelada, fácil de trabajar.', 'https://www.sephora.com/productimages/sku/s2796555-main-zoom.jpg?imwidth=1000', 'haus-labs-power-sculpt-velvet-talc-free-powder-bronzer', 112),
  ('Easy Bake Blurring Loose Baking & Setting Powder', 'HUDA BEAUTY', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Polvo suelto para sellar y hacer baking, con efecto difuminador.', 'Polvo suelto pensado tanto para sellar el maquillaje como para la técnica de baking. Fija la base y el corrector, y difumina la apariencia de líneas finas y textura. Se aplica con esponja en las zonas que más se mueven durante el día, como la ojera y la zona T.', 'https://www.sephora.com/productimages/sku/s2992055-main-zoom.jpg?imwidth=1000', 'huda-beauty-easy-bake-blurring-loose-baking-y-setting-powder', 113),
  ('#FauxFilter Brightening Under Eye Color Corrector', 'HUDA BEAUTY', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Corrector de color para ojeras, ilumina la zona bajo los ojos.', 'Corrector de color específico para la zona bajo los ojos. Neutraliza el tono azulado o amarillento de la ojera antes de aplicar el corrector, para que el resultado final se vea más limpio y luminoso. Se usa en poca cantidad y se difumina con los dedos o una esponja.', 'https://www.sephora.com/productimages/sku/s2739456-main-zoom.jpg?imwidth=1000', 'huda-beauty-fauxfilter-brightening-under-eye-color-corrector', 114),
  ('Soulgazer Lengthening Mascara + Lash Serum', 'Kosas', 'Maquillajes', 'Ojos', 'Por Encargo', 0, 'Máscara alargadora con sérum de péptidos, sin grumos.', 'Máscara de pestañas alargadora que combina el maquillaje con un sérum de péptidos que cuida la pestaña con el uso continuado. Construye volumen capa a capa sin apelmazar ni dejar grumos. Está formulada pensando en ojos sensibles y en quienes usan lentes de contacto.', 'https://www.sephora.com/productimages/sku/s3023702-main-zoom.jpg?imwidth=1000', 'kosas-soulgazer-lengthening-mascara-lash-serum', 115),
  ('Revealer Super Creamy + Brightening Concealer', 'Kosas', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Corrector cremoso de cobertura media que además cuida e ilumina la piel.', 'Corrector de cobertura media y textura muy cremosa que funciona además como contorno de ojos y tratamiento localizado. Contiene cafeína y ácido hialurónico: ilumina la zona al instante y, con el uso continuado, mejora el aspecto de la piel. No se cuartea ni se marca en las líneas.', 'https://www.sephora.com/productimages/sku/s2737351-main-zoom.jpg?imwidth=1000', 'kosas-revealer-super-creamy-brightening-concealer', 116),
  ('SoftSculpt Cream Contour & Bronzer Shaping Stick', 'MAKEUP BY MARIO', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Stick de contorno de doble punta, cobertura buildable para esculpir.', 'Stick de contorno de doble punta, con producto de un lado y brocha del otro. La cobertura es buildable, así que permite desde una sombra sutil hasta un contorno marcado. La fórmula cremosa se difumina fácil sobre la base sin arrastrarla. Es el contorno que volvió viral a la marca.', 'https://www.sephora.com/productimages/sku/s2867505-main-zoom.jpg?imwidth=1000', 'makeup-by-mario-softsculpt-cream-contour-y-bronzer-shaping-stick', 117),
  ('Soft Pop Cream Blush Stick', 'MAKEUP BY MARIO', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Rubor en stick de doble punta, color buildable y acabado dewy.', 'Rubor en stick de doble punta, con producto de un lado y brocha del otro. Da una cobertura media y buildable, con acabado dewy que deja la piel con aspecto jugoso. Se aplica directo sobre la mejilla y se difumina con la brocha incorporada, sin necesidad de otras herramientas.', 'https://www.sephora.com/productimages/sku/s2867638-main-zoom.jpg?imwidth=1000', 'makeup-by-mario-soft-pop-cream-blush-stick', 118),
  ('Artist Color Pencil Long-Lasting Lip Liner', 'MAKE UP FOR EVER', 'Maquillajes', 'Labios', 'Por Encargo', 0, 'Delineador labial de larga duración, textura cremosa.', 'Delineador labial de larga duración con textura cremosa que se desliza sin tironear. Sirve para definir el contorno, corregir la forma del labio o rellenar toda la boca como base para que el labial dure más. La punta permite trabajar con precisión en los bordes.', 'https://www.sephora.com/productimages/sku/s2946648-main-zoom.jpg?imwidth=1000', 'make-up-for-ever-artist-color-pencil-long-lasting-lip-liner', 119),
  ('Mini Artist Color Pencil & Super Boost Lip Gloss Kit', 'MAKE UP FOR EVER', 'Maquillajes', 'Labios', 'Por Encargo', 0, 'Kit con delineador labial mini y gloss Super Boost tamaño completo.', 'Kit de labios que combina un delineador Artist Color Pencil en formato mini con un gloss Super Boost de tamaño completo. La idea es definir el contorno con el lápiz y sumar brillo y volumen con el gloss encima. Práctico para llevar los dos productos coordinados.', 'https://www.sephora.com/productimages/sku/s2972727-main-zoom.jpg?imwidth=1000', 'make-up-for-ever-mini-artist-color-pencil-y-super-boost-lip-gloss-kit', 120),
  ('Radiant Creamy Concealer', 'NARS', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Corrector cremoso de cobertura media, hidratante y de acabado luminoso.', 'Corrector cremoso de cobertura media con fórmula hidratante y acabado luminoso. Cubre ojeras e imperfecciones sin resecar ni marcarse en las líneas de expresión, por lo que también funciona en pieles maduras. Es uno de los correctores más vendidos de NARS.', 'https://www.sephora.com/productimages/sku/s2172310-main-zoom.jpg?imwidth=1000', 'nars-radiant-creamy-concealer', 121),
  ('Mini Talc-Free Powder Blush', 'NARS', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Rubor en polvo sin talco, en formato mini.', 'Rubor en polvo libre de talco en formato mini, ideal para llevar en la cartera o para probar un tono nuevo sin comprar el tamaño completo. La textura en polvo se difumina de forma pareja sobre la base y permite construir el color de a poco.', 'https://www.sephora.com/productimages/sku/s2756062-main-zoom.jpg?imwidth=1000', 'nars-mini-talc-free-powder-blush', 122),
  ('Mini Multiple Blush & Sculpt Stick Duo', 'NARS', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Dúo de sticks multiuso mini para rubor y esculpir.', 'Dúo de sticks multiuso en formato mini: uno para dar color a las mejillas y otro para esculpir y dar dimensión al rostro. La textura cremosa se difumina con los dedos, así que se puede usar sin brochas. Pensado para retocar fuera de casa o viajar liviana.', 'https://www.sephora.com/productimages/sku/s2974988-main-zoom.jpg?imwidth=1000', 'nars-mini-multiple-blush-y-sculpt-stick-duo', 123),
  ('Mini Eye Sculpt Eyeshadow Palette', 'NATASHA DENONA', 'Maquillajes', 'Ojos', 'Por Encargo', 0, 'Paleta mini de sombras para definir y esculpir la mirada.', 'Paleta de sombras en formato mini pensada para esculpir y dar profundidad a la mirada. Combina tonos y texturas que permiten armar desde un look natural de día hasta uno más marcado. El tamaño reducido la hace cómoda para viajar sin resignar opciones.', 'https://www.sephora.com/productimages/sku/s2929982-main-zoom.jpg?imwidth=1000', 'natasha-denona-mini-eye-sculpt-eyeshadow-palette', 124),
  ('Mini Bronze & Glow Cheek Duo', 'NATASHA DENONA', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Dúo compacto de bronzer e iluminador en formato mini.', 'Dúo compacto en formato mini que combina bronzer e iluminador en un solo estuche. Permite dar calidez y luz al rostro con un solo producto, sin cargar dos compactos por separado. Práctico para retocar durante el día o llevar de viaje.', 'https://www.sephora.com/productimages/sku/s2204568-main-zoom.jpg?imwidth=1000', 'natasha-denona-mini-bronze-y-glow-cheek-duo', 125),
  ('Major Headlines Transition Blurring Under Eye Blush Duo', 'PATRICK TA', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Dúo de rubor para la zona bajo los ojos, con efecto difuminado.', 'Dúo de rubor pensado para aplicar en la zona alta de la mejilla y bajo los ojos, siguiendo la técnica que popularizó la marca. La combinación de texturas permite difuminar la transición entre el rubor y el resto del rostro, para un acabado suave y sin bordes marcados.', 'https://www.sephora.com/productimages/sku/s2976264-main-zoom.jpg?imwidth=1000', 'patrick-ta-major-headlines-transition-blurring-under-eye-blush-duo', 126),
  ('Warm Wishes Effortless Cream Bronzer Stick', 'Rare Beauty by Selena Gomez', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Bronzer en stick de acabado segunda piel, se difumina sin esfuerzo.', 'Bronzer en stick que da un efecto bronceado instantáneo y se funde con la piel para un acabado de segunda piel. Se aplica directo sobre la mejilla, la frente y el puente de la nariz, y se difumina con los dedos o una brocha. Pensado para usar rápido, sin herramientas ni técnica.', 'https://www.sephora.com/productimages/sku/s2518934-main-zoom.jpg?imwidth=1000', 'rare-beauty-by-selena-gomez-warm-wishes-effortless-cream-bronzer-stick', 127),
  ('Positive Light Silky Touch Highlighter', 'Rare Beauty by Selena Gomez', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Iluminador en polvo de brillo tipo vidrio, natural y duradero.', 'Iluminador en polvo que da a la piel un brillo tipo vidrio, sin partículas de glitter visibles. El resultado es luminoso pero natural, y se mantiene a lo largo del día. La textura es finísima y se difumina sobre la base sin resaltar la textura de la piel.', 'https://www.sephora.com/productimages/sku/s2629483-main-zoom.jpg?imwidth=1000', 'rare-beauty-by-selena-gomez-positive-light-silky-touch-highlighter', 128),
  ('All Day Makeup Setting Spray', 'SEPHORA COLLECTION', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Bruma fijadora de maquillaje para que dure todo el día.', 'Bruma fijadora que se aplica al final del maquillaje para sellar el look. Ayuda a que la base y el resto de los productos se mantengan en su lugar durante el día, y quita el aspecto polvoriento que dejan los polvos sueltos, unificando el acabado.', 'https://www.sephora.com/productimages/sku/s2408011-main-zoom.jpg?imwidth=1000', 'sephora-collection-all-day-makeup-setting-spray', 129),
  ('shape tape Hydrating Full Coverage Creamy Concealer', 'tarte', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Corrector cremoso de alta cobertura con fórmula hidratante.', 'Versión hidratante del corrector más vendido de tarte. Mantiene la alta cobertura que caracteriza a shape tape pero con una fórmula más cremosa, pensada para pieles secas o para quienes sienten que el original marca líneas. Cubre ojeras e imperfecciones de una sola pasada.', 'https://www.sephora.com/productimages/sku/s2821478-main-zoom.jpg?imwidth=1000', 'tarte-shape-tape-hydrating-full-coverage-creamy-concealer', 130),
  ('Cloud Crush Blurring Powder Blush', 'Too Faced', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Rubor en polvo de textura suave con efecto difuminado.', 'Rubor en polvo de textura muy suave que se difumina con facilidad y deja un acabado difuminado, sin bordes marcados. Permite construir el color de a poco, desde un rubor apenas perceptible hasta uno más intenso, sin apelmazarse sobre la base.', 'https://www.sephora.com/productimages/sku/s2642502-main-zoom.jpg?imwidth=1000', 'too-faced-cloud-crush-blurring-powder-blush', 131),
  ('Chocolate Soleil Melting Bronzing & Sculpting Stick', 'Too Faced', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Bronzer en stick de textura fundente para broncear y esculpir.', 'Bronzer en stick de textura fundente que sirve tanto para dar calidez como para esculpir el rostro. Se aplica directo sobre la piel y se difumina con los dedos o una brocha. El formato en barra lo hace práctico para retocar fuera de casa.', 'https://www.sephora.com/productimages/sku/s2772101-main-zoom.jpg?imwidth=1000', 'too-faced-chocolate-soleil-melting-bronzing-y-sculpting-stick', 132),
  ('Chocolate Soleil Matte Blurring Bronzer', 'Too Faced', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Bronzer en polvo de acabado mate con efecto difuminador.', 'Bronzer en polvo de acabado mate que además difumina la apariencia de la textura de la piel. Da calidez al rostro sin destellos ni brillo, por lo que funciona bien para el día y para contornear. Pertenece a la línea Chocolate Soleil, con aroma a cacao.', 'https://www.sephora.com/productimages/sku/s2966059-main-zoom.jpg?imwidth=1000', 'too-faced-chocolate-soleil-matte-blurring-bronzer', 133),
  ('Better Than Sex Volumizing & Lengthening Mascara', 'Too Faced', 'Maquillajes', 'Ojos', 'Por Encargo', 0, 'Máscara que da volumen, alarga y fija la curvatura de las pestañas.', 'Máscara de pestañas que suma volumen, alarga y mantiene la curvatura desde la primera pasada. El cepillo tipo reloj de arena permite llegar a la raíz y separar pestaña por pestaña. Es uno de los productos más vendidos de Too Faced y un clásico del rubro.', 'https://www.sephora.com/productimages/sku/s1533439-main-zoom.jpg?imwidth=1000', 'too-faced-better-than-sex-volumizing-y-lengthening-mascara', 134),
  ('Chocolate Soleil Multi-Use Sculpting Pencil', 'Too Faced', 'Maquillajes', 'Rostro', 'Por Encargo', 0, 'Lápiz multiuso para esculpir y definir el rostro.', 'Lápiz multiuso de la línea Chocolate Soleil, pensado para esculpir y definir los rasgos del rostro. La punta permite trabajar con precisión en zonas chicas como los laterales de la nariz o el arco de la ceja, y la textura se difumina antes de asentarse.', 'https://www.sephora.com/productimages/sku/s2966117-main-zoom.jpg?imwidth=1000', 'too-faced-chocolate-soleil-multi-use-sculpting-pencil', 135);
